In [1]:
inputs= [2.5, 1.8, 3.9]
weights = [1.3, 1.7, 2.9]
biases  = 0.5

In [4]:
output = (inputs[0]*weights[0]) + (inputs[1]*weights[1]) + (inputs[2]*weights[2]) + biases
output

18.119999999999997

## Yay Neural Networks

neuron with 3 inputs

In [5]:
inputs= [2.5, 1.8, 3.9]
weights =[
    [1.3, 1.7, 2.9],
    [1.7, 4.2, 1.1],
    [6.2, 1.3, 0.7]
]
biases=[1.2,1.6,1.9]

outputs=[]
for neuron_weights, neuron_biases in zip(weights, biases):
    neuron_output=0
    for weight, input in zip(neuron_weights,inputs):
        neuron_output+=weight*input
    neuron_output+=neuron_biases
    outputs.append(neuron_output)
outputs

[18.819999999999997, 17.700000000000003, 22.47]

## using the np

In [1]:
import numpy as np

In [ ]:
inputs= [2.5, 1.8, 3.9]
weights =[
    [1.3, 1.7, 2.9],
    [1.7, 4.2, 1.1],
    [6.2, 1.3, 0.7]
]
biases=[1.2,1.6,1.9]#iterates through the weights list
output = np.dot(inputs,weights)+biases
print(output)

[31.69 18.48 13.86]


## Batch processing

In [ ]:
inputs= [[2.5, 1.8, 3.9,2],
        [2.0,5.0,-1.0,4],
        [-1.5,2.7,2.2,5]] 
weights =[
    [1.3, 1.7, 2.9, 1.9],
    [1.7, 4.2, 1.1, 1.9],
    [6.2, 1.3, 0.7, 1.9]
]
biases=[1.2,1.6,1.9]
output = np.dot(inputs,np.array(weights).T)+biases
#why transform
#no of inputs in each batch should be equal to number of lists of weights
print(output)

[[22.62 21.5  26.27]
 [17.   32.5  27.7 ]
 [19.72 22.31  7.15]]


## layering

In [ ]:
inputs= [[2.5, 1.8, 3.9,2],
        [2.0,5.0,-1.0,4],
        [-1.5,2.7,2.2,5]] 
weights_1 =[
    [1.3, 1.7, 2.9, 1.9],
    [1.7, 4.2, 1.1, 1.9],
    [6.2, 1.3, 0.7, 1.9]
]
biases_1=[1.2,1.6,1.9]
layer_1_output = np.dot(inputs,np.array(weights_1).T)+biases_1

#layer2
weights_2 =[
    [1.7, 1.7, 2.9],
    [1.3, 6.1, 8.7],
    [1.8, 1.3, -1.2]
]
biases_2=[6.3,1.8,2.1]
layer_2_output = np.dot(layer_1_output,np.array(weights_2).T)+biases_2
print(layer_2_output)


[[157.487 390.905  39.242]
 [170.78  463.14   41.71 ]
 [ 98.486 225.732  58.019]]
