In [1]:
import numpy as np
np.random.seed(0)

In [2]:
X= [[2.5, 1.8, 3.9,2],
    [2.0,5.0,-1.0,4],
    [-1.5,2.7,2.2,5]] 

In [3]:
class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights = 0.1*np.random.randn(n_inputs,n_neurons) #for simplicity
        self.biases = np.zeros((1,n_neurons))
    
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights)+self.biases

In [4]:
layer_1=Layer_Dense(4,5)
layer_2=Layer_Dense(5,2)

In [5]:
layer_1.forward(X)
layer_2.forward(layer_1.output)
print(layer_2.output)

[[ 0.19286267 -0.06024843]
 [ 0.11458705 -0.05152382]
 [ 0.08831379 -0.16736338]]


## Activation functions

In [6]:
class ReLU:
    def forward(self,inputs):
        self.output = np.maximum(0,inputs)

In [8]:
%pip install nnfs

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\WHATEVERELSE\GeekStuff\Python\python.exe -m pip install --upgrade pip' command.


In [9]:
import nnfs
from nnfs.datasets import spiral_data

In [10]:
x,y=spiral_data(100,3)

In [11]:
layer1=Layer_Dense(2,5)
activation1=ReLU()
layer1.forward(x)
activation1.forward(layer1.output)
print(activation1.output)

[[0.         0.         0.         0.         0.        ]
 [0.00080274 0.         0.00065987 0.         0.00083796]
 [0.00082768 0.         0.0005103  0.         0.00454176]
 ...
 [0.01800099 0.         0.00336391 0.         0.26602511]
 [0.         0.16360456 0.         0.13192221 0.20328078]
 [0.         0.         0.         0.05579987 0.31271706]]
